version: '3.5'
services:
  api1:
    image: rinha
    depends_on:
      - db
  api2:
    image: rinha
    depends_on:
      - db

  nginx:
    image: nginx:latest
    volumes:
      - ./scripts/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
  db:
    image: postgres
    command: "postgres -c max_connections=200"
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: rinhabackend-java
    volumes:
      - ./scripts/script.sql:/docker-entrypoint-initdb.d/script.sql