version: '3.5'
services:
  api1:
    image: rinha
    hostname: api1
    depends_on:
      - db
    expose:
      - "8080"
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: '0.9GB'

  api2:
    image: rinha
    hostname: api2
    depends_on:
      - db
    expose:
      - "8080"
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: '0.9GB'

  nginx: # Load Balancer
    image: nginx:latest
    volumes:
      - ./scripts/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '0.5GB'

  db: # Banco de dados
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: rinhabackend-java
    deploy:
      resources:
        limits:
          cpus: '0.70'
          memory: '1.2GB'