version: '3.5'
services:
  api1:
    image: matheuspieropan/rinhabackend
    depends_on:
      - db
  api2:
    image: matheuspieropan/rinhabackend
    depends_on:
      - db
  nginx:
    image: nginx:latest
    volumes:
      - ./scripts/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
  db:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: rinhabackend-java
    volumes:
      - ./scripts/script.sql:/docker-entrypoint-initdb.d/script.sql