version: '3.5'
services:
  api1:
    image: rinha
    hostname: api1
    depends_on:
      - db
    expose:
      - "8080"
    deploy:
      resources:
        limits:
          cpus: '0.65'
          memory: '0.75GB'

  api2:
    image: rinha
    hostname: api2
    depends_on:
      - db
    expose:
      - "8080"
    deploy:
      resources:
        limits:
          cpus: '0.65'
          memory: '0.75GB'

  nginx: # Load Balancer
    image: nginx:latest
    volumes:
      - ./scripts/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.10'
          memory: '0.5GB'

  db: # Banco de dados
    image: postgres
    command: "postgres -c max_connections=200"
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: rinhabackend-java
    volumes:
        - ./script.sql:/docker-entrypoint-initdb.d/script.sql
    deploy:
      resources:
        limits:
          cpus: '0.20'
          memory: '0.5GB'