version: '3.5'
services:
  api1:
    image: matheuspieropan/rinhabackend
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "125MB"
  api2:
    image: matheuspieropan/rinhabackend
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "125MB"
  nginx:
    image: nginx:latest
    volumes:
      - ./scripts/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api1
      - api2
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "40MB"
    ports:
      - "9999:9999"
  db:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: rinhabackend-java
    volumes:
      - ./scripts/script.sql:/docker-entrypoint-initdb.d/script.sql
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "210MB"